---
- name: Prepare - install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python using native package manager
      raw: |
        set -e
        if [ -f /etc/oracle-release ]; then
          dnf install -y epel-release
          dnf install -y python39
          if ! command -v python3 >/dev/null 2>&1; then
            alternatives --set python3 /usr/bin/python3.9 2>/dev/null || \
            ln -sf /usr/bin/python3.9 /usr/bin/python3
          fi
        elif command -v apt-get; then
          apt-get update
          apt-get install -y python3 python3-apt python3-selinux
        elif command -v dnf; then
          dnf install -y python3 python3-libselinux
        elif command -v yum; then
          yum install -y python3 python3-libselinux
        else
          echo "No supported package manager found"
          exit 1
        fi
      args:
        executable: /bin/bash
      changed_when: false