---
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/library/fedora:34
    pre_build_image: true
    command: sleep infinity
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
verifier:
  name: ansible