---
- name: Prepare - install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      raw: dnf install -y python3 python3-libselinux
      args:
        executable: /bin/bash
      changed_when: false
